/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | 'Pacific/Midway'
    | 'Pacific/Niue'
    | 'Pacific/Honolulu'
    | 'Pacific/Rarotonga'
    | 'America/Anchorage'
    | 'Pacific/Gambier'
    | 'America/Los_Angeles'
    | 'America/Tijuana'
    | 'America/Denver'
    | 'America/Phoenix'
    | 'America/Chicago'
    | 'America/Guatemala'
    | 'America/New_York'
    | 'America/Bogota'
    | 'America/Caracas'
    | 'America/Santiago'
    | 'America/Buenos_Aires'
    | 'America/Sao_Paulo'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/Azores'
    | 'Atlantic/Cape_Verde'
    | 'Europe/London'
    | 'Europe/Berlin'
    | 'Africa/Lagos'
    | 'Europe/Athens'
    | 'Africa/Cairo'
    | 'Europe/Moscow'
    | 'Asia/Riyadh'
    | 'Asia/Dubai'
    | 'Asia/Baku'
    | 'Asia/Karachi'
    | 'Asia/Tashkent'
    | 'Asia/Calcutta'
    | 'Asia/Dhaka'
    | 'Asia/Almaty'
    | 'Asia/Jakarta'
    | 'Asia/Bangkok'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Tokyo'
    | 'Asia/Seoul'
    | 'Australia/Brisbane'
    | 'Australia/Sydney'
    | 'Pacific/Guam'
    | 'Pacific/Noumea'
    | 'Pacific/Auckland'
    | 'Pacific/Fiji'

export interface Config {
    auth: {
        users: UserAuthOperations
    }
    blocks: {}
    collections: {
        users: User
        media: Media
        sites: Site
        'payload-kv': PayloadKv
        'payload-locked-documents': PayloadLockedDocument
        'payload-preferences': PayloadPreference
        'payload-migrations': PayloadMigration
    }
    collectionsJoins: {}
    collectionsSelect: {
        users: UsersSelect<false> | UsersSelect<true>
        media: MediaSelect<false> | MediaSelect<true>
        sites: SitesSelect<false> | SitesSelect<true>
        'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
    }
    db: {
        defaultIDType: string
    }
    fallbackLocale: null
    globals: {}
    globalsSelect: {}
    locale: null
    widgets: {
        collections: CollectionsWidget
    }
    user: User
    jobs: {
        tasks: unknown
        workflows: unknown
    }
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string
        password: string
    }
    login: {
        email: string
        password: string
    }
    registerFirstUser: {
        email: string
        password: string
    }
    unlock: {
        email: string
        password: string
    }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: string
    name: string
    whatsapp: string
    cpf?: string | null
    cref?: string | null
    updatedAt: string
    createdAt: string
    email: string
    resetPasswordToken?: string | null
    resetPasswordExpiration?: string | null
    salt?: string | null
    hash?: string | null
    loginAttempts?: number | null
    lockUntil?: string | null
    sessions?:
        | {
              id: string
              createdAt?: string | null
              expiresAt: string
          }[]
        | null
    password?: string | null
    collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: string
    alt: string
    updatedAt: string
    createdAt: string
    url?: string | null
    thumbnailURL?: string | null
    filename?: string | null
    mimeType?: string | null
    filesize?: number | null
    width?: number | null
    height?: number | null
    focalX?: number | null
    focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
    id: string
    name: string
    /**
     * Usuário responsável por este site.
     */
    user: string | User
    template: 'template-1'
    /**
     * Endereço usado para acessar o site. Exemplo: /template1/lucas-andrade
     */
    slug: string
    published: boolean
    template1: {
        hero: {
            titlePrimary: string
            title: string
            titleHighlight: string
            desc: string
            button1text: string
            button1url: string
            /**
             * Escolha a imagem principal que aparecerá no Hero.
             */
            img: string | Media
        }
        /**
         * O Template 1 utiliza exatamente 4 métricas.
         */
        metrics: {
            /**
             * Exemplos: 8, 480, 4.9 ou 1mil.
             */
            number: string
            text: string
            id?: string | null
        }[]
        services: {
            title: string
            desc: string
            /**
             * O Template 1 utiliza exatamente 3 serviços.
             */
            cards: {
                title: string
                desc: string
                text: string
                price?: string | null
                /**
                 * Opcional. Se adicionar uma opção, é obrigatório preencher exatamente 4 opções.
                 */
                option?:
                    | {
                          text: string
                          id?: string | null
                      }[]
                    | null
                /**
                 * Link que será aberto ao clicar em Escolher Plano.
                 */
                link?: string | null
                featured: boolean
                id?: string | null
            }[]
        }
        about: {
            /**
             * Imagem que aparecerá na seção sobre você.
             */
            img: string | Media
            title: string
            desc: string
            /**
             * O Template 1 utiliza exatamente 4 diferenciais.
             */
            features: {
                title: string
                id?: string | null
            }[]
        }
        testimonials: {
            title: string
            desc: string
            /**
             * O Template 1 utiliza exatamente 4 depoimentos.
             */
            cards: {
                name: string
                text: string
                id?: string | null
            }[]
        }
        contact: {
            title: string
            titleHighlight: string
            text: string
            buttontext: string
            buttonurl: string
        }
        whatsapp: {
            enabled: boolean
            /**
             * Coloque o número com código do país e DDD, sem espaços ou símbolos.
             */
            phone: string
            message: string
        }
    }
    updatedAt: string
    createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: string
    key: string
    data:
        | {
              [k: string]: unknown
          }
        | unknown[]
        | string
        | number
        | boolean
        | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: string
    document?:
        | ({
              relationTo: 'users'
              value: string | User
          } | null)
        | ({
              relationTo: 'media'
              value: string | Media
          } | null)
        | ({
              relationTo: 'sites'
              value: string | Site
          } | null)
    globalSlug?: string | null
    user: {
        relationTo: 'users'
        value: string | User
    }
    updatedAt: string
    createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: string
    user: {
        relationTo: 'users'
        value: string | User
    }
    key?: string | null
    value?:
        | {
              [k: string]: unknown
          }
        | unknown[]
        | string
        | number
        | boolean
        | null
    updatedAt: string
    createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: string
    name?: string | null
    batch?: number | null
    updatedAt: string
    createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    name?: T
    whatsapp?: T
    cpf?: T
    cref?: T
    updatedAt?: T
    createdAt?: T
    email?: T
    resetPasswordToken?: T
    resetPasswordExpiration?: T
    salt?: T
    hash?: T
    loginAttempts?: T
    lockUntil?: T
    sessions?:
        | T
        | {
              id?: T
              createdAt?: T
              expiresAt?: T
          }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T
    updatedAt?: T
    createdAt?: T
    url?: T
    thumbnailURL?: T
    filename?: T
    mimeType?: T
    filesize?: T
    width?: T
    height?: T
    focalX?: T
    focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
    name?: T
    user?: T
    template?: T
    slug?: T
    published?: T
    template1?:
        | T
        | {
              hero?:
                  | T
                  | {
                        titlePrimary?: T
                        title?: T
                        titleHighlight?: T
                        desc?: T
                        button1text?: T
                        button1url?: T
                        img?: T
                    }
              metrics?:
                  | T
                  | {
                        number?: T
                        text?: T
                        id?: T
                    }
              services?:
                  | T
                  | {
                        title?: T
                        desc?: T
                        cards?:
                            | T
                            | {
                                  title?: T
                                  desc?: T
                                  text?: T
                                  price?: T
                                  option?:
                                      | T
                                      | {
                                            text?: T
                                            id?: T
                                        }
                                  link?: T
                                  featured?: T
                                  id?: T
                              }
                    }
              about?:
                  | T
                  | {
                        img?: T
                        title?: T
                        desc?: T
                        features?:
                            | T
                            | {
                                  title?: T
                                  id?: T
                              }
                    }
              testimonials?:
                  | T
                  | {
                        title?: T
                        desc?: T
                        cards?:
                            | T
                            | {
                                  name?: T
                                  text?: T
                                  id?: T
                              }
                    }
              contact?:
                  | T
                  | {
                        title?: T
                        titleHighlight?: T
                        text?: T
                        buttontext?: T
                        buttonurl?: T
                    }
              whatsapp?:
                  | T
                  | {
                        enabled?: T
                        phone?: T
                        message?: T
                    }
          }
    updatedAt?: T
    createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T
    data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T
    globalSlug?: T
    user?: T
    updatedAt?: T
    createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T
    key?: T
    value?: T
    updatedAt?: T
    createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T
    batch?: T
    updatedAt?: T
    createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
    data?: {
        [k: string]: unknown
    }
    width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown
}

declare module 'payload' {
    export interface GeneratedTypes extends Config {}
}
